### ISSUE TITLE
unexpected EOF while parsing

### ISSUE THREAD

**Issue by sreeramsanjay** [healthcoda/onelogin-aws-cli#2]
https://admin.us.onelogin.com/api_credentials
Onelogin API Client ID: <removed client ed>
Traceback (most recent call last):
  File "/usr/local/bin/onelogin-aws-login", line 17, in <module>
    OneloginAWS.generate_config()
  File "/usr/local/lib/python2.7/site-packages/onelogin_aws_cli/__init__.py", line 179, in generate_config
    default["client_id"] = input("Onelogin API Client ID: ")
  File "<string>", line 1
    <removed client id >
                                                                   ^
SyntaxError: unexpected EOF while parsing
[root@ip-172-28-0-98 ~]#

**Comment by sreeramsanjay** [comment]
i am able to run it after providing the input with ""
