### ISSUE TITLE
Getting a 500 error after entering OTP code and error is unable to parse the JSON

### ISSUE THREAD

**Issue by jmymy** [healthcoda/onelogin-aws-cli#3]
Trying get it to work with onelogin and I get this error after auth. 

> onelogin-aws-login
<Response [200]>
Onelogin Username: 'XXX'
Onelogin Password:
<Response [200]>
OTP Token: XXXX
<Response [500]>

`Traceback (most recent call last):
  File "/usr/local/bin/onelogin-aws-login", line 26, in <module>
    api.save_credentials()
  File "/usr/local/lib/python2.7/site-packages/onelogin_aws_cli/__init__.py", line 140, in save_credentials
    self.assume_role()
  File "/usr/local/lib/python2.7/site-packages/onelogin_aws_cli/__init__.py", line 115, in assume_role
    self.get_saml_assertion()
  File "/usr/local/lib/python2.7/site-packages/onelogin_aws_cli/__init__.py", line 110, in get_saml_assertion
    headers, params)
  File "/usr/local/lib/python2.7/site-packages/onelogin_aws_cli/__init__.py", line 57, in request
    raise Exception("Error: {}".format(res.json()))
  File "/usr/local/lib/python2.7/site-packages/requests/models.py", line 866, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded`

MacOS 10.12
Onelogin API key is for auth only
AWS login works from onelogin into AWS console.
`pip install onelogin_aws_cli
Requirement already satisfied: onelogin_aws_cli in /usr/local/lib/python2.7/site-packages
Requirement already satisfied: boto3 in /usr/local/lib/python2.7/site-packages (from onelogin_aws_cli)
Requirement already satisfied: requests in /usr/local/lib/python2.7/site-packages (from onelogin_aws_cli)
Requirement already satisfied: botocore<1.6.0,>=1.5.0 in /usr/local/lib/python2.7/site-packages (from boto3->onelogin_aws_cli)
Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in /usr/local/lib/python2.7/site-packages (from boto3->onelogin_aws_cli)
Requirement already satisfied: s3transfer<0.2.0,>=0.1.10 in /usr/local/lib/python2.7/site-packages (from boto3->onelogin_aws_cli)
Requirement already satisfied: docutils>=0.10 in /usr/local/lib/python2.7/site-packages (from botocore<1.6.0,>=1.5.0->boto3->onelogin_aws_cli)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /usr/local/lib/python2.7/site-packages (from botocore<1.6.0,>=1.5.0->boto3->onelogin_aws_cli)
Requirement already satisfied: futures<4.0.0,>=2.2.0; python_version == "2.6" or python_version == "2.7" in /usr/local/lib/python2.7/site-packages (from s3transfer<0.2.0,>=0.1.10->boto3->onelogin_aws_cli)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python2.7/site-packages (from python-dateutil<3.0.0,>=2.1->botocore<1.6.0,>=1.5.0->boto3->onelogin_aws_cli)`

**Comment by jmymy** [comment]
ok so 
the username has to be entered with ' around it as its expecting a string.
password does not need the '
OTP token needs the ' as its expecting a string.

Also,
The Onelogin API credentials need to be "Manage All" type and not just Auth only.
